# Generated by Django 5.2.5 on 2025-08-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('turn_number', models.IntegerField()),
                ('dice_roll_1', models.CharField(blank=True, max_length=50, null=True)),
                ('dice_roll_2', models.CharField(blank=True, max_length=50, null=True)),
                ('final_dice_state', models.CharField(max_length=50)),
                ('chosen_category', models.CharField(max_length=50)),
                ('score_obtained', models.IntegerField()),
                ('score_state_before', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='yachtgame.gamesession')),
            ],
        ),
    ]
