# Generated by Django 5.2.5 on 2025-08-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachtgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnlog',
            name='kept_after_roll_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='turnlog',
            name='kept_after_roll_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
