# Generated by Django 5.2.5 on 2025-08-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachtgame', '0003_gamesession_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
