# Generated by Django 5.2.5 on 2025-08-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachtgame', '0004_gamesession_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnlog',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnlog',
            name='player_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='turnlog',
            name='score_state_before',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='turnlog',
            constraint=models.UniqueConstraint(fields=('game_session', 'turn_number', 'player_name'), name='unique_turn_per_game'),
        ),
        migrations.AddConstraint(
            model_name='turnlog',
            constraint=models.UniqueConstraint(fields=('game_session', 'player_name', 'chosen_category'), name='unique_category_per_game'),
        ),
    ]
